### ISSUE TITLE
ModuleNotFoundError: No module named 'SimpleHTTPServer'

### ISSUE THREAD

**Issue by ducalpha** [atstp/wasabi#2]
I got an error: `ModuleNotFoundError: No module named 'SimpleHTTPServer'` when running `demo-page.sh`.

For Python 3, the [last line in demo-page.sh](https://github.com/atstp/wasabi/blob/2c4ba6dc46b6cf051a6a66a8466b18b5cc36c02b/bin/demo-page.sh#L173) should be changed to `python http.server`.

**Comment by atstp** [comment]
thanks, it's updated
